module.exports = [
  {
    id: 1,
    customer_info_id: 1,
    file_name: "document1.pdf",
    file_path: "/path/to/files/document1.pdf",
    date_created: 1674892800,
  },
  {
    id: 2,
    customer_info_id: 2,
    file_name: "report.pdf",
    file_path: "/path/to/files/report.pdf",
    date_created: 1674800100,
  },
  {
    id: 3,
    customer_info_id: 3,
    file_name: "presentation.pdf",
    file_path: "/path/to/files/presentation.pdf",
    date_created: 1674707400,
  },
  {
    id: 4,
    customer_info_id: 4,
    file_name: "invoice.pdf",
    file_path: "/path/to/files/invoice.pdf",
    date_created: 1674614700,
  },
  {
    id: 5,
    customer_info_id: 5,
    file_name: "manual.pdf",
    file_path: "/path/to/files/manual.pdf",
    date_created: 1674522000,
  },
  {
    id: 6,
    customer_info_id: 6,
    file_name: "contract.pdf",
    file_path: "/path/to/files/contract.pdf",
    date_created: 1674429300,
  },
  {
    id: 7,
    customer_info_id: 7,
    file_name: "proposal.pdf",
    file_path: "/path/to/files/proposal.pdf",
    date_created: 1674336600,
  },
  {
    id: 8,
    customer_info_id: 8,
    file_name: "agreement.pdf",
    file_path: "/path/to/files/agreement.pdf",
    date_created: 1674243900,
  },
  {
    id: 9,
    customer_info_id: 9,
    file_name: "catalog.pdf",
    file_path: "/path/to/files/catalog.pdf",
    date_created: 1674151200,
  },
  {
    id: 10,
    customer_info_id: 10,
    file_name: "presentation2.pdf",
    file_path: "/path/to/files/presentation2.pdf",
    date_created: 1674058500,
  },
  {
    id: 11,
    customer_info_id: 11,
    file_name: "proposal2.pdf",
    file_path: "/path/to/files/proposal2.pdf",
    date_created: 1673965800,
  },
  {
    id: 12,
    customer_info_id: 12,
    file_name: "agreement2.pdf",
    file_path: "/path/to/files/agreement2.pdf",
    date_created: 1673873100,
  },
  {
    id: 13,
    customer_info_id: 13,
    file_name: "document2.pdf",
    file_path: "/path/to/files/document2.pdf",
    date_created: 1673780400,
  },
  {
    id: 14,
    customer_info_id: 14,
    file_name: "invoice2.pdf",
    file_path: "/path/to/files/invoice2.pdf",
    date_created: 1673687700,
  },
  {
    id: 15,
    customer_info_id: 15,
    file_name: "manual2.pdf",
    file_path: "/path/to/files/manual2.pdf",
    date_created: 1673595000,
  },
  {
    id: 16,
    customer_info_id: 16,
    file_name: "report2.pdf",
    file_path: "/path/to/files/report2.pdf",
    date_created: 1673502300,
  },
  {
    id: 17,
    customer_info_id: 17,
    file_name: "presentation3.pdf",
    file_path: "/path/to/files/presentation3.pdf",
    date_created: 1673409600,
  },
  {
    id: 18,
    customer_info_id: 18,
    file_name: "contract2.pdf",
    file_path: "/path/to/files/contract2.pdf",
    date_created: 1673316900,
  },
  {
    id: 19,
    customer_info_id: 19,
    file_name: "catalog2.pdf",
    file_path: "/path/to/files/catalog2.pdf",
    date_created: 1673224200,
  },
  {
    id: 20,
    customer_info_id: 20,
    file_name: "presentation4.pdf",
    file_path: "/path/to/files/presentation4.pdf",
    date_created: 1673131500,
  },
];
