module.exports = [
  {
    customer_info_id: 1,
    profile_name: "Ian Pinili",
    number: "(778)-855-3645",
    tech_number: "11975",
    email: "gianpinili@gmail.com",
    position: "Automotive Technician",
  },
  {
    customer_info_id: 2,
    profile_name: "Christi Gentle",
    number: "(604)-123-4567",
    tech_number: "10244",
    email: "christi.gentle@company.com",
    position: "Automotive Technician",
  },
  {
    customer_info_id: 3,
    profile_name: "George Coop",
    number: "(604)-653-6542",
    tech_number: "10016",
    email: "george.coop@company.com",
    position: "Automotive Technician",
  },
  {
    customer_info_id: 4,
    profile_name: "Jack E. Chan",
    number: "(604)-658-5441",
    tech_number: "00132",
    email: "jack.e.chan@company.com",
    position: "Automotive Technician Apprentice",
  },
  {
    customer_info_id: 5,
    profile_name: "Russell Nguyen",
    number: "(604)-564-7898",
    tech_number: "11554",
    email: "russell.nguyen@company.com",
    position: "Lube Tech",
  },
];
